### ISSUE TITLE
Make README consistent with code on file extension ('.ex' vs '.exs')

### ISSUE THREAD

**Issue by EugZol** [joekain/bmark#5]
README reads:

> To create a benchmark with bmark, create a file ending in `_bmark.exs`

While code reads:

```
Path.wildcard("bmark/**/*_bmark.ex")
```

[Source](https://github.com/joekain/bmark/blob/master/lib/mix/tasks/bmark.ex#L32)

One of the above should be changed to match the other.

**Comment by joekain** [comment]
@EugZol, thanks for filing this.  Can you take a look at pull request #8 and review if the new documentation makes sense?

**Comment by joekain** [comment]
I'm going to go ahead and close this, @EugZol if you have any feedback on the change feel free to comment or open another issue.
