### ISSUE TITLE
Avoid GC to get in the way of benchmarking

### ISSUE THREAD

**Issue by mr-bt** [joekain/bmark#9]
I didn't run into this issue but I'm evaluating this lib for benchmarking and GC pop out as a question.

I wonder if is worthy to do a :erlang.garbage_collect before every run or execute the :timer.tc in a short living process.

**Comment by joekain** [comment]
Hi @mr-bt,

I'm not sure what I understand what you mean by "execute the :timer.tc in a short living process".  Can you elaborate?

Regarding calling :erlang.garbage_collect: That's an interesting point.  I can see this two different ways:
1. Bmark should try to minimize GC during the benchmar so you can focus on your code.
2. Bmark should allow GC to occur naturally so you can measure its effect on your program.

Or is your point that you are seeing GC that happens late in the benchmark run after the real work in your program is done?

**Comment by mr-bt** [comment]
Hi,

I'll try to summarize how I think the bechmarks run and then try to explain my line of thought. I might not have the clear idea how things work as I think I do, so please correct me if I'm wrong.

When I was going through the code I've realized that all benchs happen in the same process (`:Bmark`). First the benchs specs are added to the `:Bmark` proc and then the mix task calls `Bmark.Server.run_benchmarks`. When `Bmark.Server.run_benchmarks` runs, for each bench spec the :time.tc is called. At this point I've got curious how `:timer.tc` works and to check if the function evaluated runs on the caller process or runs in another process. It turns out that it runs on the caller process (https://github.com/erlang/otp/blob/a2670f0822fc6729df956c8ec8c381340ff0a5fb/lib/stdlib/src/timer.erl#L157-L200).

So I've got to the conclusion that my code is not isolated (process wise) when the benchmark runs which can lead to GC being triggered not by the benchmark in particular but by other benchmark(s) or even by running that particular benchmark a certain number of times [1]. 

This is my view.

When I say "execute the :timer.tc in a short living process" I mean spawn a process that will execute `:timer.tc` and return the exectution time.

> 1. Bmark should try to minimize GC during the benchmar so you can focus on your code.
> 2. Bmark should allow GC to occur naturally so you can measure its effect on your program.

If a process is spawned to execute the `:timer.tc` both 1. and 2. are achieved. 
By calling `:erlang.garbage_collect` only 1. is achieved. However, by tuning the `:Bmark` proc GC is possible to get close to get 2.

All together this might not be an issue. ATM is all theoretical as I don't have an use case that demonstrates the GC is getting into to way of my benchmarks. Just food for thought :smiley:

[1] One might want to benchmark what's the impact of running a function x number of times. That can be achieved by adding more options or by defining the benchmark like this:

```
  bmark :runner do
    1..5 |> Enum.each(fn _ -> IO.puts ":runner test is running" end)
  end
```

**Comment by joekain** [comment]
Hi @mr-bt,

Thanks for explanation.  So, I see now that the problem is that when running several benchmarks the accumulation of tests may lead to GC that wouldn't happen with just a single test.  

Yeah, looking at it that way it makes to start with a clean GC slate at the beginning of each individual benchmark.  Then as you pointed out, GC can occur during the benchmark if the test does enough work to trigger it naturally.

I can make this change in the next couple of days, or if to take it on I would happily accept a pull request.

Thanks!
